version: '3'

vars:
  NEXT_VERSION:
    sh: npx --yes entro-version version:next

  NEXT_MAJOR_VERSION:
    sh: npx --yes entro-version version:next --commit-and-tag-version-flag="--release-as=major"

tasks:
  install-deps:
    desc: "Install dependencies"
    cmds:
      - |
        cd cli
        cargo build
  test:
    desc: "Run the tests"
    cmds:
      - |
        cd cli
        cargo test

  release:
    desc: "Run a cargo release from develop to main using git flow"
    cmds:
      - |
        cargo set-version {{.NEXT_VERSION}}
        npx --yes entro-version release --main-branch-name=main

  release-major:
    desc: "Run a major release from develop to main using git flow"
    cmds:
      - |
        cargo set-version {{.NEXT_MAJOR_VERSION}}
        npx --yes entro-version release --main-branch-name=main --commit-and-tag-version-flag="--release-as=major"
  
  build-binary:
    desc: "Build the binary"
    cmds:
      - |
        cd cli
        cargo build --release

  build:
    desc: "Build the binary - the assumption is that this is done from the main branch"
    cmds:

