version: '3'

tasks:
  install-deps:
    desc: "Install dependencies"
    cmds:
      - |
        cd cli
        cargo build
  test:
    desc: "Run the tests"
    cmds:
      - |
        cd cli
        cargo test