version: '3'

tasks:
  install-deps:
    desc: "Install dependencies"
    cmds:
      - |
        cd cli
        cargo build
  test:
    desc: "Run the tests"
    cmds:
      - |
        cd cli
        cargo test

  release:
    desc: "Run a cargo release from develop to main using git flow"
    cmds:
      - cargo release minor --execute

  release-major:
    desc: "Run a standard release from develop to main using git flow"
    cmds:
      - cargo release minor --execute

  build-binary:
    desc: "Build the binary"
    cmds:
      - |
        cd cli
        cargo build --release

  build:
    desc: "Build the binary - the assumption is that this is done from the main branch"
    cmds:

