[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-modules = "0.22.0"
clap = "4.5.29"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
rayon = "1.10.0"
merkle_hash = "3.7.0"
