name: "Build"

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install cross
        uses: taiki-e/install-action@cross

      - name: Build the binaries for each supported platform
        run: task build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: release/
          if-no-files-found: error
