name: "Unit Tests"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Task
      - name: Install Task
        uses: arduino/setup-task@v2

      # Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          profile: minimal

      # Install cross for cross-compilation
      - name: Install cross
        run: cargo install cross

      # Display Rust version
      - name: Display Rust version
        run: rustc --version

      # Install Wine from the default Ubuntu repository
      - name: Install Wine
        run: sudo apt install --install-recommends wine64

      - name: Install winetricks
        run: sudo apt install winetricks

      - name: Install Windows libraries
        run: |
          winetricks -q vcrun2019  # Install Visual C++ 2019 Redistributable
          winetricks -q corefonts  # Install core Windows fonts

      # Run the tests
      - name: Run the tests for the supported platforms
        run: task test-all